name: DEFLECTION ARMOR.com
favicon: null
layout_spectrum: 0.17831
typography_spectrum: 0.82314
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090909'
    - '#cab99f'
    - '#433e38'
    - '#9b6e57'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: sign-ups
    item: null
    url: null
